name: Swift

on: [push]
jobs:
  build:
    runs-on: macos-latest

    # steps:
      # - run: sudo xcode-select -s "/Applications/Xcode_13.4.1.app"
      # - uses: actions/checkout@v3
      # - uses: fwal/setup-swift@2040b795e5c453c3a05fcb8316496afc8a74f192
      #   with:
      #     swift-version: "5.5"
      # - name: Build
      #   run: swift build -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk iphonesimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "arm64-apple-ios15.0-simulator"
      # - name: Run tests
      #   run: swift test -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk iphonesimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "arm64-apple-ios15.0-simulator"


    steps:
      - uses: actions/checkout@v3
      - uses: fwal/setup-swift@2040b795e5c453c3a05fcb8316496afc8a74f192
        with:
          swift-version: "5.5"
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
